# common properties

encryptionPath=v1/identity/encrypt?isInternal=false
internalEncryptionPath=v1/identity/encrypt?isInternal=true
encodePath=v1/identity/encode
decodePath=v1/identity/decode
decryptPath=/idauthentication/v1/internal/decrypt
encodeFilePath=v1/identity/encodeFile
decodeFilePath=v1/identity/decodeFile/?fileName=cbeff
validateSignaturePath=v1/identity/validateSign?signature=$signature$
splitEncryptedData=v1/identity/splitEncryptedData
getPartnerCertificateUrl=/v1/partnermanager/partners/{partnerId}/certificate
putPartnerRegistrationUrl=/v1/partnermanager/partners
uploadCACertificateUrl=/v1/partnermanager/partners/certificate/ca/upload
uploadIntermediateCertificateUrl=/v1/partnermanager/partners/certificate/ca/upload
uploadPartnerCertificateUrl=/v1/partnermanager/partners/certificate/upload
masterSchemaURL=/v1/masterdata/idschema/latest
demoAppVersion=1.2.1-SNAPSHOT
#partner certificate refId, used for getting the partner certificate
passwordForAddIdentity=12341234_Aa
passwordToReset=12341234_AaB