DeleteBioExtractorConfigurationNegativeScenarios:
  Pms_DeleteBioExtractorConfiguration_With_Invalid_Id_Neg:
    endPoint: /v1/partnermanager/bio-extractor-configurations/{bioExtractorConfigurationId}
    uniqueIdentifier: TC_PMS_DeleteBioExtractorConfigurationNegativeScenarios_01
    description: Validate that Bio Extractor Configuration deletion fails when an invalid id is provided in the request.
    role: partneradmin
    restMethod: patch
    inputTemplate: pms/BioExtractorConfiguration/DeleteBioExtractorConfiguration/DeleteBioExtractorConfiguration
    outputTemplate: pms/error
    input: '{
      "id": "invalid",
      "version": "1.0",
      "requestTime": "$TIMESTAMP$",
      "bioExtractorConfigurationId": "$ID:CreateBioExtractorConfiguration_All_Valid_Smoke_reqsid_sid_id$",
      "status": "DELETED"
}'
    output: '{
      "errors": [
        {
          "errorCode": "PMS_REQUEST_ERROR_002"
        }
      ]
}'

  Pms_DeleteBioExtractorConfiguration_With_Invalid_Version_Neg:
    endPoint: /v1/partnermanager/bio-extractor-configurations/{bioExtractorConfigurationId}
    uniqueIdentifier: TC_PMS_DeleteBioExtractorConfigurationNegativeScenarios_02
    description: Validate that Bio Extractor Configuration deletion fails when an invalid version is provided in the request.
    role: partneradmin
    restMethod: patch
    inputTemplate: pms/BioExtractorConfiguration/DeleteBioExtractorConfiguration/DeleteBioExtractorConfiguration
    outputTemplate: pms/error
    input: '{
      "id": "mosip.pms.bioextractor.configuration.delete.patch",
      "version": "invalid",
      "requestTime": "$TIMESTAMP$",
      "bioExtractorConfigurationId": "$ID:CreateBioExtractorConfiguration_All_Valid_Smoke_reqsid_sid_id$",
      "status": "DELETED"
}'
    output: '{
      "errors": [
        {
          "errorCode": "PMS_REQUEST_ERROR_003"
        }
      ]
}'

  Pms_DeleteBioExtractorConfiguration_With_Empty_Version_Neg:
    endPoint: /v1/partnermanager/bio-extractor-configurations/{bioExtractorConfigurationId}
    uniqueIdentifier: TC_PMS_DeleteBioExtractorConfigurationNegativeScenarios_03
    description: Validate that Bio Extractor Configuration deletion fails when an empty version is provided in the request.
    role: partneradmin
    restMethod: patch
    inputTemplate: pms/BioExtractorConfiguration/DeleteBioExtractorConfiguration/DeleteBioExtractorConfiguration
    outputTemplate: pms/error
    input: '{
      "id": "mosip.pms.bioextractor.configuration.delete.patch",
      "version": "",
      "requestTime": "$TIMESTAMP$",
      "bioExtractorConfigurationId": "$ID:CreateBioExtractorConfiguration_All_Valid_Smoke_reqsid_sid_id$",
      "status": "DELETED"
}'
    output: '{
      "errors": [
        {
          "errorCode": "PMS_REQUEST_ERROR_003"
        }
      ]
}'

  Pms_DeleteBioExtractorConfiguration_With_Invalid_Status_Neg:
    endPoint: /v1/partnermanager/bio-extractor-configurations/{bioExtractorConfigurationId}
    uniqueIdentifier: TC_PMS_DeleteBioExtractorConfigurationNegativeScenarios_04
    description: Validate that Bio Extractor Configuration deletion fails when an invalid status value is provided in the request.
    role: partneradmin
    restMethod: patch
    inputTemplate: pms/BioExtractorConfiguration/DeleteBioExtractorConfiguration/DeleteBioExtractorConfiguration
    outputTemplate: pms/error
    input: '{
      "id": "mosip.pms.bioextractor.configuration.delete.patch",
      "version": "1.0",
      "requestTime": "$TIMESTAMP$",
      "bioExtractorConfigurationId": "$ID:CreateBioExtractorConfiguration_All_Valid_Smoke_reqsid_sid_id$",
      "status": "invalid"
}'
    output: '{
      "errors": [
        {
          "errorCode": "PMS_PRT_099"
        }
      ]
}'

  Pms_DeleteBioExtractorConfiguration_With_Empty_Status_Neg:
    endPoint: /v1/partnermanager/bio-extractor-configurations/{bioExtractorConfigurationId}
    uniqueIdentifier: TC_PMS_DeleteBioExtractorConfigurationNegativeScenarios_05
    description: Validate that Bio Extractor Configuration deletion fails when status is empty in the request.
    role: partneradmin
    restMethod: patch
    inputTemplate: pms/BioExtractorConfiguration/DeleteBioExtractorConfiguration/DeleteBioExtractorConfiguration
    outputTemplate: pms/error
    input: '{
      "id": "mosip.pms.bioextractor.configuration.delete.patch",
      "version": "1.0",
      "requestTime": "$TIMESTAMP$",
      "bioExtractorConfigurationId": "$ID:CreateBioExtractorConfiguration_All_Valid_Smoke_reqsid_sid_id$",
      "status": ""
}'
    output: '{
      "errors": [
        {
          "errorCode": "PMS_REQUEST_ERROR_001"
        }
      ]
}'

  Pms_DeleteBioExtractorConfiguration_With_Invalid_BioExtractorConfigurationId_Neg:
    endPoint: /v1/partnermanager/bio-extractor-configurations/{bioExtractorConfigurationId}
    uniqueIdentifier: TC_PMS_DeleteBioExtractorConfigurationNegativeScenarios_06
    description: Validate that Bio Extractor Configuration deletion fails when an invalid bioExtractorConfigurationId is provided.
    role: partneradmin
    restMethod: patch
    inputTemplate: pms/BioExtractorConfiguration/DeleteBioExtractorConfiguration/DeleteBioExtractorConfiguration
    outputTemplate: pms/error
    input: '{
      "id": "mosip.pms.bioextractor.configuration.delete.patch",
      "version": "1.0",
      "requestTime": "$TIMESTAMP$",
      "bioExtractorConfigurationId": "invalid-bioextractorconfiguration-id",
      "status": "DELETED"
}'
    output: '{
      "errors": [
        {
          "errorCode": "PMS_PRT_275"
        }
      ]
}'

  Pms_DeleteBioExtractorConfiguration_With_Empty_BioExtractorConfigurationId_Neg:
    endPoint: /v1/partnermanager/bio-extractor-configurations/{bioExtractorConfigurationId}
    uniqueIdentifier: TC_PMS_DeleteBioExtractorConfigurationNegativeScenarios_07
    description: Validate that Bio Extractor Configuration deletion fails when bioExtractorConfigurationId is empty.
    role: partneradmin
    restMethod: patch
    checkOnlyStatusCodeInResponse: true
    inputTemplate: pms/BioExtractorConfiguration/DeleteBioExtractorConfiguration/DeleteBioExtractorConfiguration
    outputTemplate: pms/responseCode
    input: '{
      "id": "mosip.pms.bioextractor.configuration.delete.patch",
      "version": "1.0",
      "requestTime": "$TIMESTAMP$",
      "bioExtractorConfigurationId": "",
      "status": "DELETED"
}'
    output: '{
      "responseCode": "404"
}'

  Pms_DeleteBioExtractorConfiguration_With_AlreadyDeleted_Id_Neg:
    endPoint: /v1/partnermanager/bio-extractor-configurations/{bioExtractorConfigurationId}
    uniqueIdentifier: TC_PMS_DeleteBioExtractorConfigurationNegativeScenarios_08
    description: Validate that Bio Extractor Configuration deletion fails when an already deleted configuration ID is provided.
    role: partneradmin
    restMethod: patch
    inputTemplate: pms/BioExtractorConfiguration/DeleteBioExtractorConfiguration/DeleteBioExtractorConfiguration
    outputTemplate: pms/error
    input: '{
      "id": "mosip.pms.bioextractor.configuration.delete.patch",
      "version": "1.0",
      "requestTime": "$TIMESTAMP$",
      "bioExtractorConfigurationId": "$ID:CreateBioExtractorConfiguration_For_AlreadyDeleted_sid_id$",
      "status": "DELETED"
}'
    output: '{
      "errors": [
        {
          "errorCode": "PMS_PRT_275"
        }
      ]
}'
