package io.mosip.pms.ida.constant;

public enum EventType {

	MISP_UPDATED, POLICY_UPDATED, APIKEY_UPDATED, PARTNER_UPDATED, CA_CERTIFICATE_UPLOADED, APIKEY_APPROVED,
	MISP_LICENSE_GENERATED, MISP_LICENSE_UPDATED, PARTNER_REGISTRED, APIKEY_STATUS_UPDATED, APIKEY_EXPIRED
}
