package io.mosip.testrig.apirig.partner.utils;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import org.apache.log4j.Level;
import org.apache.log4j.Logger;
import org.testng.SkipException;

import io.mosip.testrig.apirig.dbaccess.DBManager;
import io.mosip.testrig.apirig.dto.TestCaseDTO;
import io.mosip.testrig.apirig.testrunner.BaseTestCase;
import io.mosip.testrig.apirig.utils.AdminTestUtil;
import io.mosip.testrig.apirig.utils.GlobalConstants;
import io.mosip.testrig.apirig.utils.SkipTestCaseHandler;
import io.restassured.response.Response;

public class PMSUtil extends AdminTestUtil {

	private static final Logger logger = Logger.getLogger(PMSUtil.class);
	
	public static List<String> testCasesInRunScope = new ArrayList<>();
	
	public static void setLogLevel() {
		if (PMSConfigManager.IsDebugEnabled())
			logger.setLevel(Level.ALL);
		else
			logger.setLevel(Level.ERROR);
	}
	
	public static String isTestCaseValidForExecution(TestCaseDTO testCaseDTO) {
		String testCaseName = testCaseDTO.getTestCaseName();
		currentTestCaseName = testCaseName;
		
		int indexof = testCaseName.indexOf("_");
		String modifiedTestCaseName = testCaseName.substring(indexof + 1);

		addTestCaseDetailsToMap(modifiedTestCaseName, testCaseDTO.getUniqueIdentifier());
				
		if (!testCasesInRunScope.isEmpty()
				&& testCasesInRunScope.contains(testCaseDTO.getUniqueIdentifier()) == false) {
			throw new SkipException(GlobalConstants.NOT_IN_RUN_SCOPE_MESSAGE);
		}
		
		// Handle extra workflow dependencies
		if (testCaseDTO != null && testCaseDTO.getAdditionalDependencies() != null
				&& AdminTestUtil.generateDependency == true) {
			addAdditionalDependencies(testCaseDTO);
		}
		
		if (SkipTestCaseHandler.isTestCaseInSkippedList(testCaseName)) {
			throw new SkipException(GlobalConstants.KNOWN_ISSUES);
		}
		return testCaseName;
	}
	
	public static String inputStringKeyWordHandeler(String jsonString, String testCaseName) {
		if (jsonString.contains("$IDPREDIRECTURI$")) {
			jsonString = replaceKeywordValue(jsonString, "$IDPREDIRECTURI$",
					ApplnURI.replace(GlobalConstants.API_INTERNAL, "healthservices") + "/userprofile");
		}
		if (jsonString.contains("$LICENSE_KEY_NAME$")) {
			String licenseKeyName = "MISP_API_Automation_" + UUID.randomUUID().toString().substring(0, 8);
			jsonString = jsonString.replace("$LICENSE_KEY_NAME$", licenseKeyName);
		    logger.info("Generated dynamic licenseKeyName: " + licenseKeyName);
		}
		return jsonString;
	}
	
	public static String replaceKeywordValue(String jsonString, String keyword, String value) {
		if (value != null && !value.isEmpty())
			return jsonString.replace(keyword, value);
		else {
			if (keyword.contains("$ID:"))
				throw new SkipException("Marking testcase as skipped as required field is empty " + keyword
						+ " please check the results of testcase: " + getTestCaseIDFromKeyword(keyword));
			else
				throw new SkipException("Marking testcase as skipped as required field is empty " + keyword);
		}

	}
	
	public static void DbCleanRevamp() {
		BaseTestCase.currentModule = GlobalConstants.PARTNER_MANAGEMENT_SERVICE;
		DBManager.executeDBQueries(PMSConfigManager.getPMSDbUrl(), PMSConfigManager.getPMSDbUser(),
				PMSConfigManager.getPMSDbPass(), PMSConfigManager.getPMSDbSchema(),
				getGlobalResourcePath() + "/" + "config/partnerRevampDataDeleteQueries.txt");
				
		DBManager.executeDBQueries(PMSConfigManager.getKeymangrDbUrl(), PMSConfigManager.getKeymangrDbUser(),
				PMSConfigManager.getKeymangrDbPass(), PMSConfigManager.getKMDbSchema(),
				getGlobalResourcePath() + "/" + "config/partnerRevampDataDeleteQueriesForKeyMgr.txt");

		DBManager.executeDBQueries(PMSConfigManager.getIdaDbUrl(), PMSConfigManager.getIdaDbUser(),
				PMSConfigManager.getPMSDbPass(), PMSConfigManager.getIdaDbSchema(),
				getGlobalResourcePath() + "/" + "config/partnerRevampDataDeleteQueriesForIDA.txt");
		
		DBManager.executeDBQueries(PMSConfigManager.getPMSDbUrl(), PMSConfigManager.getPMSDbUser(),
				PMSConfigManager.getPMSDbPass(), PMSConfigManager.getPMSDbSchema(),
				getGlobalResourcePath() + "/" + "config/pmsDataDeleteQueries.txt");
		
		DBManager.executeDBQueries(PMSConfigManager.getKMDbUrl(), PMSConfigManager.getKMDbUser(),
				PMSConfigManager.getKMDbPass(), PMSConfigManager.getKMDbSchema(),
				getGlobalResourcePath() + "/" + "config/keyManagerDataDeleteQueries.txt");
	}
	
	public void validateResponse(Response response, String testCaseName, String idKeyName) {
		if (response != null
				&& (response.asString().contains("PMS_FEATURE_001") || response.asString().contains("PMS_FEATURE_002")
						|| response.asString().contains("PMS_FEATURE_003"))) {
			if (idKeyName != null) {
				String[] fieldNames = idKeyName.split(",");
				for (String fieldName : fieldNames) {
					writeAutoGeneratedId(testCaseName, fieldName, "randomData");
				}
			}
			throw new SkipException(PMSConstants.FEATURE_NOT_SUPPORTED_PMSREVAMP);

		}
	}

	public void validateResponse(Response response, String testCaseName) {
		validateResponse(response, testCaseName, null);
	}
}