\c mosip_pms 

\ir ddl/pms-auth_policy.sql
\ir ddl/pms-auth_policy_h.sql
\ir ddl/pms-device_detail.sql
\ir ddl/pms-device_detail_sbi.sql
\ir ddl/pms-ftp_chip_detail.sql
\ir ddl/pms-misp.sql
\ir ddl/pms-misp_license.sql
\ir ddl/pms-otp_transaction.sql
\ir ddl/pms-partner.sql
\ir ddl/pms-partner_contact.sql
\ir ddl/pms-partner_h.sql
\ir ddl/pms-partner_policy.sql
\ir ddl/pms-partner_policy_bioextract.sql
\ir ddl/pms-partner_policy_credential_type.sql
\ir ddl/pms-partner_policy_request.sql
\ir ddl/pms-partner_type.sql
\ir ddl/pms-policy_group.sql
\ir ddl/pms-reg_device_sub_type.sql
\ir ddl/pms-reg_device_type.sql
\ir ddl/pms-secure_biometric_interface.sql
\ir ddl/pms-secure_biometric_interface_h.sql
\ir ddl/pms-tspid_seq.sql
\ir ddl/pms-oidc_client.sql
\ir ddl/pms-user_details.sql
\ir ddl/pms-fk.sql