\c mosip_pms 

GRANT CONNECT
   ON DATABASE mosip_pms
   TO pmsuser;

GRANT USAGE
   ON SCHEMA pms
   TO pmsuser;

GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES
   ON ALL TABLES IN SCHEMA pms
   TO pmsuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA pms
	GRANT SELECT,INSERT,UPDATE,DELETE,REFERENCES ON TABLES TO pmsuser;

