package io.mosip.pms.common.constant;

public enum EventType {

	MISP_UPDATED,POLICY_UPDATED,APIKEY_UPDATED,PARTNER_UPDATED,CA_CERTIFICATE_UPLOADED,MISP_LICENSE_GENERATED,MISP_LICENSE_UPDATED,PARTNER_APPROVED,APIKEY_APPROVED
}
