GetValueForConfigKey:
   Pms_GetValueForConfigKey_allValid_smoke:
      endPoint: /v1/policymanager/policies/config/{key}
      uniqueIdentifier: TC_PMS_GetValueForConfigKey_01
      description: Validate that the value for a given configuration key is retrieved successfully for a valid request
      role: partner
      checkErrorsOnlyInResponse: true
      restMethod: get
      inputTemplate: pms/GetValueForConfigKey/getValueForConfigKey
      outputTemplate: pms/GetValueForConfigKey/getValueForConfigKeyResult
      input: '{
      "key": "pmp.datashare.policy.schema",
    "requesttime": "$TIMESTAMP$"
}'
      output: '{
    "key": "pmp.datashare.policy.schema",
  } '
  
   Pms_GetValueForConfigKey_allValid_smoke:
      endPoint: /v1/policymanager/policies/config/{key}
      uniqueIdentifier: TC_PMS_GetValueForConfigKey_02
      description: Validate that all configuration key values are retrieved successfully for valid requests
      role: partner
      checkErrorsOnlyInResponse: true
      restMethod: get
      inputTemplate: pms/GetValueForConfigKey/getValueForConfigKey
      outputTemplate: pms/GetValueForConfigKey/getValueForConfigKeyResult
      input: '{
      "key": "abcd",
    "requesttime": "$TIMESTAMP$"
}'
      output: '{
    "key": "abcd",
  } '